### ISSUE TITLE
backdoor?

### ISSUE THREAD

**Issue by akhribfarouk** [danielplohmann/apiscout#30] opened 2021-01-10 10:39 UTC
Are you serious man?
**https://www.virustotal.com/gui/file/8cba2a5cecd8b3bddd8837789603e9cf18ddc7015fe84394a27799190be4cc1d/detection**
---------------------------------------
why is this??

**Comment by danielplohmann** [comment] 2021-01-10 11:34
duplicate of #29.

**Closed by danielplohmann** 2021-01-10 11:34 UTC
